BlogCoders/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    
    path('', views.home, name='home'),
    path('bloghome', views.blog, name='blog'),
    path('blogpost/<str:slug>', views.blogpost, name='blogpost'),
    path('addblog', views.addblog, name='addblog'),
    path('editblog/<str:sno>', views.editblog, name='editblog'),
    path('delete_data/<str:sno>', views.delete_data, name='delete_data'),
    path('search', views.search, name='search'),
    path('contact', views.contact, name='contact'),
    
]

blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
	sno = models.AutoField(primary_key=True)
	title = models.CharField(max_length=200)
	content = models.TextField(null=True, blank=True)
	short_desc = models.CharField(max_length=250, default="", null=True, blank=True)
	slug = models.CharField(max_length=100)
	time = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from blog.models import Blog
from django_update_from_dict import update_from_dict

# Create your views here.


def home(request):
	if request.method == "POST":		
		Title = request.POST.get('title')		
		Content = request.POST.get('content')
		Short_Desc = request.POST.get('short_desc')
		Slug = request.POST.get('slug')
		Blog.objects.create(title=Title,  content=Content, short_desc=Short_Desc, slug=Slug)
		return redirect('/')

	return render(request, 'index.html')



def blog(request):
	blogs = Blog.objects.all()
	context = {'blogs':blogs}
	return render(request, 'bloghome.html', context)

def blogpost(request, slug):
	blog = Blog.objects.filter(slug = slug ).first()
	context = {'blog':blog}
	return render(request, 'blogpost.html', context)

def addblog(request):
	if request.method == "POST":		
		Title = request.POST.get('title')		
		Content = request.POST.get('content')
		Short_Desc = request.POST.get('short_desc')
		Slug = request.POST.get('slug')
		Blog.objects.create(title=Title,  content=Content, short_desc=Short_Desc, slug=Slug)
		return redirect('/bloghome')

	return render(request, 'addblog.html')

def editblog(request,sno):
	Current_Object = Blog.objects.get(sno=sno)
	if request.method == "POST":
		Sno = request.POST.get('sno')
		Title = request.POST.get('title')
		Content = request.POST.get('content')
		Short_Desc = request.POST.get('short_desc')
		Slug = request.POST.get('slug')
		update_from_dict(Current_Object, dict(sno=Sno, title=Title,  content=Content, short_desc=Short_Desc, slug=Slug), commit=True)

		return redirect('/bloghome')


	return render(request, 'editblog.html', {'Current_Object':Current_Object})

def delete_data(request,sno):
	data = Blog.objects.get(sno=sno)
	data.delete()
	return redirect('/bloghome')



def search(request):
	return render(request, 'search.html')

def contact(request):
	return render(request, 'contact.html')

templates/addblog.html
{% extends 'base.html' %}

{% block title %} Home {% endblock title %}

{% block homeactive %} active {% endblock %}

{% block body %}

{% load static %}

<div class="container w-50 mb-5">
	<h3 class="text-center my-5"> Post Your Blog </h3>
	<form method="POST">
		{% csrf_token %}
	  <div class="form-group ">
	    <label for="formGroupExampleInput">Blog Title</label>
	    <input type="text" class="form-control" name="title" id="formGroupExampleInput" placeholder="Example input">
	  </div>

	  <div class="form-group">
   		 <label for="id_content">Blog Content</label>
 	     <textarea class="form-control" name="content" id="id_content" rows="6"></textarea>
  	  </div>

  	  <div class="form-group">
   		 <label for="exampleFormControlTextarea4">Expert Content</label>
 	     <textarea class="form-control" name="short_desc" id="exampleFormControlTextarea4" rows="2"></textarea>
  	  </div>

	  <div class="form-group">
	    <label for="formGroupExampleInput3">Blog-Sluge</label>
	    <input type="textarea" class="form-control" name="slug" id="formGroupExampleInput3" placeholder="Another input">
	  </div>
	  <div>
	  	<button type="submit" class="btn btn-primary">Submit</button>
	  </div>

	</form>
	
</div>

{% endblock body %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>

    

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">BlogCoder</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% block homeactive %} {% endblock homeactive %}">
        <a class="nav-link" href="/"> Home </span></a>
      </li>
      <li class="nav-item {% block bloghomeactive %} {% endblock bloghomeactive %} ">
        <a class="nav-link" href="bloghome">Blog</a>
      </li>
      <li class="nav-item {% block contactactive %} {% endblock contactactive %}">
        <a class="nav-link" href="contact">Contact</a>
      </li>
     
    </ul>
    <form action="search" method="get" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


  {% block body %} {% endblock body %}

</div>



<div class="container-fluid bg-dark mt-20">
  <footer class="footer py-1">
    <p class="text-center text-light py-0"> copyrigth @2022 All right reserved </p>
  </footer>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/bloghome.html
{% extends 'base.html' %}

{% block title %} BloG Home {% endblock title %}

{% block bloghomeactive %} active {% endblock bloghomeactive %}

{% block body %}

<div class="container-fluid bg-light"> 

<h4 class="text-center py-4"> Welcome to BlogCoder </h4>

{% for blog in blogs %}
{% load static %}


  <div class="container w-50 mx-auto"> 
   <div class="card">
    <div class="card-header bg-dark">
      
    </div>
    <div class="card-body">
      <h4 class="card-title"><a href="blogpost/{{blog.slug}}" class="text-dark">{{blog.title}}</a></h4>
      <p class="card-text">{{blog.short_desc|slice:270}}</p>
      <p class="card-text">{{blog.time}}</p>
      <a href="blogpost/{{blog.slug}}" class="btn btn-dark">Read More</a>
      
      <a href="delete_data/{{blog.sno}}" class="btn btn-dark float-right mx-2" type="button">Delete</a>
        <a href="editblog/{{blog.sno}}" class="btn btn-dark float-right mx-2" type="button">edit</a>
        
      
    </div>
    

  </div>
</div>


<br>


{% endfor %}

</div>
{% endblock body %}

templates/blogpost.html
{% extends 'base.html' %}

{% block title %} Blog Post {% endblock title %}

{% block body %}


<h4> Welcome to BlogCoder </h4>



<div class="container"> 
 <div class="card">
  <div class="card-header">
    Blog Coder
  </div>
  <div class="card-body">
    <h5 class="card-title">{{blog.title}}</h5>
    <p class="card-text">{{blog.content|safe}}</p>

    <a href="#" class="btn btn-dark float-right mx-2" type="button">Delete</a>
        <a href="editblog/{{blog.sno}}" class="btn btn-dark float-right mx-2" type="button">edit</a>
    
    
  </div>
</div>
</div>
<br>







 {% endblock body %}

templates/contact.html
{% extends 'base.html' %}

{% block title %} Contact Us {% endblock title %}

{% block contactactive %} active {% endblock contactactive %}

{% block body %} Contact Derictory {% endblock body %}

templates/editblog.html
{% extends 'base.html' %}

{% block title %} Home {% endblock title %}

{% block homeactive %} active {% endblock %}

{% block body %}

{% load static %}

<div class="container w-50 mb-5">
	<h3 class="text-center my-5"> Post Your Blog </h3>
	<form method="POST">
		{% csrf_token %}
	  <div class="form-group ">
	    <label for="formGroupExampleInput">Blog Title</label>
	    <input type="text" class="form-control" name="title" value="{{Current_Object.title}}" id="formGroupExampleInput" placeholder="Example input">
	  </div>

  	  

	  <div class="form-group">
	    <label for="formGroupExampleInput4">Blog-Sluge</label>
	    <input type="textarea" class="form-control" name="slug" value="{{Current_Object.slug}}" id="formGroupExampleInput4" placeholder="Another input">
	  </div>

	  <div class="form-group">
	    <label for="formGroupExampleInput4">Time</label>
	    <input type="textarea" class="form-control" name="time" value="{{Current_Object.time}}" id="formGroupExampleInput4" placeholder="Another input">
	  </div>
	  
	  <div>
	  	<button type="submit" class="btn btn-primary">Submit</button>
	  </div>

	</form>
	
</div>

{% endblock body %}

templates/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock title %}

{% block homeactive %} active {% endblock %}

{% block body %}

{% load static %}

<div class="container-fluid my-0 px-0">
	<div id="carouselIndicators" class="carousel slide " data-ride="carousel">
	  <ol class="carousel-indicators">
	    <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
	    <li data-target="#carouselIndicators" data-slide-to="1"></li>
	    <li data-target="#carouselIndicators" data-slide-to="2"></li>
	  </ol>
	  <div class="carousel-inner">
	    <div class="carousel-item active">
	      <img class="d-block w-100" src="{% static 'img/slider1.jpg' %}"  alt="First slide" width="1200" height="450">
	    </div>
	    <div class="carousel-item">
	      <img class="d-block w-100" src="{% static 'img/slider2.jpg' %}" alt="second slide" width="1200" height="450">
	    </div>
	    <div class="carousel-item">
	      <img class="d-block w-100" src="{% static 'img/slider3.jpg' %}" alt="third slide" width="1200" height="450">
	    </div>
	  </div>
	  <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
	    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
	    <span class="carousel-control-next-icon" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
	
</div>
 
<div class="container">
<div class="container row">
	
	<div class="col-md-4 my-5">
		<img class="rounded mx-auto d-block" src="{% static 'img/icon1.png' %}" height="50">
		<div class="text-center">
			<p><h4>What is Lorem Ipsum? </h4> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the...</p>
		</div>
	</div>



	<div class="col-md-4 text-center my-5">
		<img class="rounded mx-auto d-block" src="{% static 'img/icon1.png' %}" height="50">
		<div class="text-center">
			<p class="text-center"><h3>What is Lorem Ipsum? </h3> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the...</p>
		</div>
	</div>

	<div class="col-md-4 my-5">
		<img class="rounded mx-auto d-block" src="{% static 'img/icon1.png' %}" height="50">
		<div class="text-center">
			<p class="text-center"><h3>What is Lorem Ipsum? </h3> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the...</p>
		</div>
	</div>

	<div class="text-center mx-auto">
		<a type="button" href="addblog" class="btn btn-primary text-center my-5" > Add Your New Blog </a>
	</div>
</div>


{% endblock body %}

templates/search.html
{% extends 'base.html' %}

{% block title %} Search Bar {% endblock title %}

{% block body %}   Search Page is here{% endblock body %}

templates/tiny.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

    <script>
      tinymce.init({
        selector: '#mytextarea'
      });
    </script>

  </head>

  <body>
  <h1>TinyMCE Quick Start Guide</h1>
    <form method="post">
      <textarea id="mytextarea">Hello, World!</textarea>
    </form>
  </body>
</html>